apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-z7y6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-z7y6
    app.kubernetes.io/part-of: node-express-hello-1
  name: node-express-hello-z7y6
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: node-express-hello-z7y6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: node-express-hello-z7y6
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/node-express-hello-1/node-express-hello-z7y6@sha256:6815dadf01bd9c25c2f8fcc799369d29c364d5b639eb740f2c8259fd887fd06d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
