apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello-z7y6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello-z7y6
    app.kubernetes.io/part-of: node-express-hello-1
  name: node-express-hello-z7y6
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: node-express-hello-z7y6
status:
  loadBalancer: {}
